# Generated by Django 4.2.7 on 2023-11-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.CharField(max_length=255)),
                ('f2', models.CharField(max_length=255)),
                ('f3', models.CharField(max_length=255)),
                ('f4', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FiltredData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('qty', models.CharField(max_length=255)),
            ],
        ),
    ]
